### ISSUE TITLE
Quests that need to be developed or revised

### ISSUE THREAD

**Issue by dudantas** [opentibiabr/otservbr-global-datapack#276]
Quests that need to be developed where NPC's or scripts are present incompletely or nonexistently.
If you know of any more, please leave it in the comments I will add in no issue. According to what we are fixing, we will mark them as resolved.
Thanks to all those who reported bugs in the quests, but for the sake of organization and ease of finding issues, it is best to stay that way.

**_Outfit quests:_**
- [ ] (Revision) - [Pirate Outfit](https://tibia.fandom.com/wiki/Pirate_Outfits_Quest/Spoiler) (#2405)

- [ ] (Develop) - [Poltergeist Outfits](https://tibia.fandom.com/wiki/Poltergeist_Outfits_Quest/Spoiler) (#925)

 - [ ] (Revision) - [Druid Outfit](https://tibia.fandom.com/wiki/Druid_Outfits_Quest/Spoiler) (#1533)

**_Regular quests that need to be revised:_**
- [ ] (Revision) - [Meriana Quest](https://tibia.fandom.com/wiki/Meriana_Quest/Spoiler) (#1173)

- [ ] (Revision) - [The Gravedigger of Drefia](https://tibia.fandom.com/wiki/The_Gravedigger_of_Drefia_Quest/Spoiler)
Taste Of Ashes cannot use chalk in the purple flame to obtain the ashes of the shadow. Cannot proceed with the quest after this part.
02:50 You see a strange fire. ItemID: 21430, Action ID: 4637 decayTo:21431 
Position: 32983, 32376, 11

- [ ] (Revision) - [Cults of Tibia Quest ](https://tibia.fandom.com/wiki/Cults_of_Tibia_Quest)(#2417, opentibiabr/otservbr-global#2313, opentibiabr/otservbr-global#2270, opentibiabr/otservbr-global#2169, opentibiabr/otservbr-global#2168, opentibiabr/otservbr-global#2167, opentibiabr/otservbr-global#2166, opentibiabr/otservbr-global#2165)

- [ ] (Revision) - [Grimvale](https://tibia.fandom.com/wiki/Grimvale_Quest/Spoiler)

- [ ] (Revision) - [The Shattered Isles](https://tibia.fandom.com/wiki/The_Shattered_Isles_Quest/Spoiler) (#2404)

- [ ] (Revision) - [Waterskin of Mead](https://tibia.fandom.com/wiki/Waterskin_of_Mead_Quest/Spoiler)

- [ ] (Revision) - [Power Bolts](https://tibia.fandom.com/wiki/Power_Bolts_Quest/Spoiler)

- [ ] (Revision) - [Blood Herb](https://tibia.fandom.com/wiki/Blood_Herb_Quest/Spoiler)

- [ ] (Revision) - [Rottin Wood and the Married Men](https://tibia.fandom.com/wiki/Rottin_Wood_and_the_Married_Men_Quest/Spoiler)

- [ ] (Revision) - [Forgotten Knowledge Quest](https://tibia.fandom.com/wiki/Forgotten_Knowledge_Quest/Spoiler) (#899, opentibiabr/otservbr-global#1013, opentibiabr/otservbr-global#2416, opentibiabr/otservbr-global#2327)

- [ ] (Revision) - [Heart of Destruction](https://tibia.fandom.com/wiki/Heart_of_Destruction_Quest/Spoiler) (#2267, opentibiabr/otservbr-global#2239, opentibiabr/otservbr-global#2078)

- [ ] (Revision) - [Hidden Threats](https://tibia.fandom.com/wiki/Hidden_Threats_Quest/Spoiler) (#1005)

- [ ] (Revision) - [Lower Roshamuul](https://tibia.fandom.com/wiki/Roshamuul_Quest/Spoiler) (#740)

- [ ] (Revision) - [The Ancient Tombs](https://tibia.fandom.com/wiki/The_Ancient_Tombs_Quest/Spoiler) (#1988, opentibiabr/otservbr-global#2050)

- [ ] (Revision) - [Wrath of the Emperor](https://tibia.fandom.com/wiki/Wrath_of_the_Emperor_Quest/Spoiler) (#1949)

- [ ] (Revision) - [The New Frontier](https://tibia.fandom.com/wiki/The_New_Frontier_Quest/Spoiler) (#2060)

- [ ] (Revision) - [Children of the Revolution](https://tibia.fandom.com/wiki/Children_of_the_Revolution_Quest/Spoiler) (#2061)

- [ ] (Revision) - [The Secret Library](https://tibia.fandom.com/wiki/The_Secret_Library_Quest/Spoiler) (#1005, opentibiabr/otservbr-global#2345, opentibiabr/otservbr-global#2328)

- [x] (Revision) - [Dangerous Depts Quest](https://tibia.fandom.com/wiki/Dangerous_Depths_Quest) (#2414)

- [ ] (Revision) - [Secret Service](https://tibia.fandom.com/wiki/Secret_Service_Quest/Spoiler) (#2344)

- [ ] (Revision) - [The Explorer Society](https://tibia.fandom.com/wiki/The_Explorer_Society_Quest/Spoiler) (#1276, opentibiabr/otservbr-global#1533, opentibiabr/otservbr-global#2210)

- [ ] (Revision) - [The Inquisition](https://tibia.fandom.com/wiki/The_Inquisition_Quest/Spoiler) (#1310)

- [ ] (Revision) - [In Service of Yalahar](https://tibia.fandom.com/wiki/In_Service_of_Yalahar_Quest/Spoiler) (#1311, opentibiabr/otservbr-global#1910)

- [ ] (Revision) -[ The Pits of Inferno](https://tibia.fandom.com/wiki/The_Pits_of_Inferno_Quest/Spoiler) (#1711)

- [ ] (Revision) - [Killing in the Name of...](https://tibia.fandom.com/wiki/Killing_in_the_Name_of..._Quest/Spoiler) (#2175, opentibiabr/otservbr-global#1706, opentibiabr/otservbr-global#1069, opentibiabr/otservbr-global#1952, opentibiabr/otservbr-global#2443)

- [ ] (Revision) - [Ferumbras Ascension](https://tibia.fandom.com/wiki/Ferumbras'_Ascension_Quest/Spoiler) (#1739, opentibiabr/otservbr-global#2290, opentibiabr/otservbr-global#2079)

**_Regular quests that need to be developed: (A quest listed here maybe is missing the entire quest or just part of it)_**

- [x] (Develop) - [The Order of the Lion](https://tibia.fandom.com/wiki/The_Order_of_the_Lion_Quest) (#2216)

- [ ] (Develop) - [Grave Danger](https://tibia.fandom.com/wiki/Grave_Danger_Quest/Spoiler) (#1696, opentibiabr/otservbr-global#2197)

- [ ] (Develop) - [Rest in Hallowed Ground](https://tibia.fandom.com/wiki/Rest_in_Hallowed_Ground_Quest/Spoiler)
Need the script for the tombs
AID from 4210 to 4224
Position(33218,31669,7 and 33202,31685,8)

- [ ] (Develop) - [Mintwallin Cyclops](https://tibia.fandom.com/wiki/Mintwallin_Cyclops_Quest/Spoiler)
The reward chests are empty (Position: 32592, 32097, 14)

- [ ] (Develop) - [The Dream Courts](https://tibia.fandom.com/wiki/The_Dream_Courts_Quest/Spoiler)

- [ ] (Develop) - [Twenty Miles Beneath the Sea](https://tibia.fandom.com/wiki/Twenty_Miles_Beneath_the_Sea_Quest/Spoiler)

- [ ] (Develop) - [Sinatuki](https://tibia.fandom.com/wiki/Sinatuki_Quest/Spoiler)

- [ ] (Develop) - [Cartography 101](https://tibia.fandom.com/wiki/Cartography_101_Quest/Spoiler)

- [ ] (Develop) - [Krailos](https://tibia.fandom.com/wiki/Krailos_Quest/Spoiler)

- [ ] (Develop) - [Blood Brothers](https://tibia.fandom.com/wiki/Blood_Brothers_Quest/Spoiler)

- [ ] (Develop) - [The Hunt for the Sea Serpent](https://tibia.fandom.com/wiki/The_Hunt_for_the_Sea_Serpent_Quest/Spoiler)

- [ ] (Develop) - [Treasure Hunt](https://tibia.fandom.com/wiki/Treasure_Hunt_Quest/Spoiler)

- [ ] (Develop) - [Machinery of War](https://tibia.fandom.com/wiki/Machinery_of_War_Quest/Spoiler)

- [ ] (Develop) - [The Isle of Evil](https://tibia.fandom.com/wiki/The_Isle_of_Evil_Quest/Spoiler)

- [ ] (Develop) - [To Blind the Enemy](https://tibia.fandom.com/wiki/To_Blind_the_Enemy_Quest/Spoiler)

- [ ] (Develop) - [The Repenters](https://tibia.fandom.com/wiki/The_Repenters_Quest/Spoiler)

- [ ] (Develop) - [Top of the City](https://tibia.fandom.com/wiki/Top_of_the_City_Quest/Spoiler)

- [ ] (Develop) - [Goblin Merchant](https://tibia.fandom.com/wiki/Goblin_Merchant_Quest/Spoiler)

- [ ] (Develop) - [Jack to the Future](https://tibia.fandom.com/wiki/Jack_to_the_Future_Quest/Spoiler) (Required finish the Sea of Light Quest)

- [ ] (Develop) - [Venore Daily Tasks](https://tibia.fandom.com/wiki/Venore_Daily_Tasks_Quest/Spoiler)

- [ ] (Develop) - [Pilgrimage of Ashes](https://tibia.fandom.com/wiki/Pilgrimage_of_Ashes_Quest/Spoiler)

- [ ] (Develop) - [Tower Defence](https://tibia.fandom.com/wiki/Tower_Defence_Quest/Spoiler)

- [ ] (Develop) - [The Scatterbrained Sorcerer](https://tibia.fandom.com/wiki/The_Scatterbrained_Sorcerer_Quest/Spoiler)

- [ ] (Develop) - [Research and Development](https://tibia.fandom.com/wiki/Research_and_Development_Quest/Spoiler) (Required finish the Sea of Light Quest)

- [ ] (Develop) - [Opticording Sphere](https://tibia.fandom.com/wiki/Opticording_Sphere_Quest/Spoiler)

- [ ] (Develop) - [Roshamuul](https://tibia.fandom.com/wiki/Roshamuul_Quest/Spoiler) (#779, opentibiabr/otservbr-global#2178, opentibiabr/otservbr-global#2419)
 
- [ ] (Develop) - [The Curse Spreads](https://tibia.fandom.com/wiki/Grimvale_Quest/Spoiler#The_Curse_Spreads) (#1005)

- [ ] (Develop) - [Killmaresh](https://tibia.fandom.com/wiki/Kilmaresh_Quest/Spoiler) (#1005)

- [ ] (Develop) - [Feaster of Souls](https://tibia.fandom.com/wiki/Feaster_of_Souls_Quest/Spoiler) (related to poltergeist) (#925)

- [ ] (Develop) - [Soul War Quest](https://tibia.fandom.com/wiki/Soul_War_Quest/Spoiler) (#2460)

**_Regular quests related to World Changes:_**

- [ ] (Develop) - [A Piece of Cake World Change](https://tibia.fandom.com/wiki/A_Piece_of_Cake/Spoiler) (#1005)

- [ ] (Develop) - [The Mummy's Curse World Change](https://tibia.fandom.com/wiki/The_Mummy%27s_Curse_World_Change/Spoiler) (#151)

**_Regular quests that is already implemented: (Not all quests are listed on this issue!)_**

- [x] (Developed) - Deeplings World Change

- [x] (Developed) - Kilmaresh Quest

- [x] (Developed) - Liquid Black Quest

- [x] (Developed) - The Lost Brothers Quest

- [x] (Developed) - The Cursed Crystal Quest

- [x] (Developed) - The Paradox Tower Quest

- [x] (Developed) - Lion's Rock (#1005)

- [x] (Developed) - Sea of Light Quest

- [x] (Developed) - First Dragon Quest

- [x] (Developed) - Threatened Dreams Quest

**Comment by AdversarioV** [comment]
On the quest threatened dreams the pile of bones besides the sleeping wolf is not working

14:59 You see a dead human.
Client ID: 6082
Position: 32949, 31810, 7

**Comment by AdversarioV** [comment]
- Ape city quest, first mission is to retrieve cave moss from this door but even after taking the quest it doesn't open the door

11:39 You see a closed door.
Client ID: 1698, Action ID: 51068
Position: 32781, 32910, 8

**Comment by AdversarioV** [comment]
- Demon Oak quest asks you for the 6666 task demon, but if you talk to oldrak and say "Demon Oak" he asks you for an axe and 1000 gps,  it skips the requirement for the 6666 demon task also, quest is not tracked on quest log

**Comment by AdversarioV** [comment]
On the quest "Hidden Threats Quest" Corym Ratter does nothing when you say hi/help/yes

**Comment by sircurse** [comment]
> nothing when you say hi/help/yes

Please test PR #586

**Comment by AdversarioV** [comment]
- POI quest the first rewards is in this pile of bones but clicking the body does not give you loot

17:19 You see a slain skeleton.
Client ID: 5972, Action ID: 2000, Unique ID: 56221
Decays to: 4285
Position: 32832, 32277, 10

**Comment by rigis1** [comment]
In Service of Yalahar
Problem in:
Mission 03: Death to the Deathbringer
can't progress in this section, both Palimuth and Yalahari notes don't gives progress.

**Comment by rigis1** [comment]
### Secret Service
Emma first talk to join (emma.lua 136 line) problem.
Emma says both lines.

**Comment by rigis1** [comment]
### Liquid Black Quest
Missing quest log entry after talking with Spectulus.

**Comment by rigis1** [comment]
### Lion's Rock
Problem with:
- [ ] You must complete 3 trials to progress, `it doesn't really matter in which order.`
- [ ] Now that you have the Translation Scroll, you must go to certain parts of the map to decipher the scroll. The scroll will automatically activate when you stand on specific tiles. There are 4 tiles that must be walked near to activate the scroll, `there is no specific order needed`.

**Comment by rigis1** [comment]
### Cults of Tibia Quest
- [ ] Angelo talking (getTopic wrong value)
- [ ] Boss fight

**Comment by AdversarioV** [comment]
Was "The secret library" quest developed? im seeing some chests giving doors as rewards instead of let's say "ebony piece" (Asura Palace)

**Comment by AdversarioV** [comment]
[Blood Herb](https://tibia.fandom.com/wiki/Blood_Herb_Quest/Spoiler) quest is working fine, just tested on 5 characters
